api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: false
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
